// <auto-generated />
namespace Covid19_Dashboard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RenameEmployementNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameEmployementNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202008051524555_RenameEmployementNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
